version: "3.9"

services:
  local-rerank:
    image: local-rerank:latest
    container_name: local-rerank
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - CUDA_VISIBLE_DEVICES=0,1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
